# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa941a8e588cdff8c76286ed59e0f6bdb32ab26357242c61b3b0607dfd32957609b31bdb4c38bb6feb97c90fd1727cc355e8c52e50536e8583da539987399355

test:
  secret_key_base: 8fc1c5873704e3114dc1242f4ee480962114349c33a2a4e67cff8522e548d14dbf3f12319c9b51c5cf56b9029dfd199d90887e3064bcdd546d95cfc2a7ef0b76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
